-- Phase 6a — Enable pgvector for Mastra's `PgVector` semantic-recall store.
--
-- Mastra's `PgVector` creates its own tables in the `mastra` schema on first
-- use (alongside `PostgresStore`'s tables), so this migration only installs
-- the extension. Extensions are database-scoped, not schema-scoped, so it
-- doesn't matter where the CREATE EXTENSION runs from — what matters is
-- that pgvector is available before Mastra's auto-init runs at app boot.
--
-- `IF NOT EXISTS` makes this safe to re-run on databases that already have
-- pgvector installed (e.g. local dev DBs that were brought up via the
-- `pgvector/pgvector` Docker image which pre-creates the extension).
CREATE EXTENSION IF NOT EXISTS vector;
